### ISSUE TITLE
redis-oplog changes?

### ISSUE THREAD

**Issue by brianlukoff** [quavedev/meteor-packages#3]
I've been experiencing some hard-to-reproduce issues in production with `rc.2` of the MCP version of redis-oplog (which I believe is from [this PR](https://github.com/cult-of-coders/redis-oplog/pull/405)), and wondering what changes were made to the `quave:redis-oplog` version -- is this version working well in production?

**Comment by filipenevola** [comment]
As far as we know yes @brianlukoff.

We are aware of some problems when Monti APM agent is also included but besides that it is working fine.

@matheusccastroo any other issues that you can mention here?

**Comment by brianlukoff** [comment]
Thanks for the info! What are the issues you've run into with Monti? We started using it with Monti and haven't had any issues (although since we are on the 3.0 Monti beta we don't get any redis-oplog stats in Monti).

**Comment by matheusccastroo** [comment]
@brianlukoff actually it wasn't really related to `redis-oplog`. We faced some issues where the `async` stack traces were getting mixed, but this is actually an issue on `monti` itself - so yeah, the `redis-oplog` is running fine.

**Comment by filipenevola** [comment]
Closing this issue as Matheus confirmed our redis-oplog version works greatly in our client.

Thanks ;)

**Comment by zodern** [comment]
@matheusccastroo would you be able to send me the details on the issue with the Monti APM agent?
